main: nl.trydev07.betterkitpvp.Core
name: BetterKitPvP
version: 0.0.1
author: TryDev07
website: https://github.com/TryDev07

commands:
  setspawn:
    description: set the spawn for the server
  AddRandomSpawn:
    description: add a random spawnpoint
  help:
    description: help command
  Portal:
    description: Create/Delete a portal
  shop:
    description: set/remove shop
